### ISSUE TITLE
error while running main

### ISSUE THREAD

**Issue by cli0** [benedekrozemberczki/graph2vec#1]
I installed all the dependencies as specified in the README and ran the example as given in the repo. I get the following error:

```
0it [00:00, ?it/s]Feature extraction started.



/datadisk/Workspace/test/graph2vec/venv/lib/python3.6/site-packages/gensim/models/doc2vec.py:566: UserWarning: The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.
Optimization started.

  warnings.warn("The parameter `iter` is deprecated, will be removed in 4.0.0, use `epochs` instead.")
/datadisk/Workspace/test/graph2vec/venv/lib/python3.6/site-packages/gensim/models/doc2vec.py:570: UserWarning: The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.
  warnings.warn("The parameter `size` is deprecated, will be removed in 4.0.0, use `vector_size` instead.")
2018-11-10 21:59:24,869 : INFO : collecting all words and their counts
2018-11-10 21:59:24,869 : INFO : collected 0 word types and 0 unique tags from a corpus of 0 examples and 0 words
2018-11-10 21:59:24,869 : INFO : Loading a fresh vocabulary
2018-11-10 21:59:24,869 : INFO : effective_min_count=5 retains 0 unique words (0% of original 0, drops 0)
2018-11-10 21:59:24,869 : INFO : effective_min_count=5 leaves 0 word corpus (0% of original 0, drops 0)
2018-11-10 21:59:24,869 : INFO : deleting the raw counts dictionary of 0 items
2018-11-10 21:59:24,869 : INFO : sample=0.0001 downsamples 0 most-common words
2018-11-10 21:59:24,869 : INFO : downsampling leaves estimated 0 word corpus (0.0% of prior 0)
2018-11-10 21:59:24,869 : INFO : estimated required memory for 0 words and 128 dimensions: 0 bytes
2018-11-10 21:59:24,869 : INFO : resetting layer weights
Traceback (most recent call last):
  File "/datadisk/Workspace/test/graph2vec/src/graph2vec.py", line 131, in <module>
    main(args)
  File "/datadisk/Workspace/test/graph2vec/src/graph2vec.py", line 125, in main
    alpha = args.learning_rate)
  File "/datadisk/Workspace/test/graph2vec/venv/lib/python3.6/site-packages/gensim/models/doc2vec.py", line 615, in __init__
    end_alpha=self.min_alpha, callbacks=callbacks)
  File "/datadisk/Workspace/test/graph2vec/venv/lib/python3.6/site-packages/gensim/models/doc2vec.py", line 795, in train
    queue_factor=queue_factor, report_delay=report_delay, callbacks=callbacks, **kwargs)
  File "/datadisk/Workspace/test/graph2vec/venv/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 1081, in train
    **kwargs)
  File "/datadisk/Workspace/test/graph2vec/venv/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 536, in train
    total_words=total_words, **kwargs)
  File "/datadisk/Workspace/test/graph2vec/venv/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 1187, in _check_training_sanity
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model

Process finished with exit code 1
```

Any suggestion what could be going wrong?

**Comment by benedekrozemberczki** [comment]
Are You sure that it iterates through the right data repo? The above code suggests that the glob.glob() is on an empty folder.

EDIT 1.: Yes I tried it out, if You delete the json files I get the exact same error message.

**Comment by cli0** [comment]
I cloned your repo and ran the main function. I did not change anything in the code.

**Comment by benedekrozemberczki** [comment]
What is your OS?

**Comment by cli0** [comment]
My OS is Ubuntu 18.04 but I just figured out the error thanks to your observation. You have hardcoded the directory paths as  `'./dataset/'` . If I switch to a relative path like ` '../dataset/'`  then everything gets picked up as it should.

**Comment by benedekrozemberczki** [comment]
Cool.
