### ISSUE TITLE
ValueError: 11 columns passed, passed data had 14 columns

### ISSUE THREAD

**Issue by Shawnmhy** [benedekrozemberczki/graph2vec#31]
Hello, I am trying to run graph2vec on my own dataset. It seems like each graph will use different values of dimensions, as I encountered the following error during my run: 

`Traceback (most recent call last):
  File "graph2vec.py", line 137, in <module>
    main(args)
  File "graph2vec.py", line 133, in main
    save_embedding(args.output_path, model, graphs, args.dimensions)
  File "graph2vec.py", line 106, in save_embedding
    out = pd.DataFrame(out, columns=column_names)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 474, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 461, in to_arrays
    return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 500, in _list_to_arrays
    raise ValueError(e) from e
ValueError: 11 columns passed, passed data had 14 columns`
Could you please suggest how to solve this problem?

**Comment by benedekrozemberczki** [comment]
Yes, I would recommend using the KarateClub library. It provides a richer set of whole graph embedding techniques. Could you star it and hit a follow on GitHub?
