### ISSUE TITLE
ValueError while using the default Dataset

### ISSUE THREAD

**Issue by AkshatSood** [benedekrozemberczki/graph2vec#33]
I was having trouble using the tool with my dataset, so I tried using the default dataset using the following command:

`python src/graph2vec.py --dimensions 32`

But even on the default dataset provided, I get the following error: 

```
Traceback (most recent call last):
  File "src/graph2vec.py", line 129, in <module>
    main(args)
  File "src/graph2vec.py", line 125, in main
    save_embedding(args.output_path, model, graphs, args.dimensions)
  File "src/graph2vec.py", line 98, in save_embedding
    out.append([int(identifier)] + list(model.docvecs["g_"+identifier]))
ValueError: invalid literal for int() with base 10: 'dataset\\0'
```

I tried fixing the error for the string format, but that raises some KeyErrors. Could I kindly get some assistance with this? 

Edit: I have attached the KeyError below:
```
Traceback (most recent call last):
  File "src/graph2vec.py", line 130, in <module>
    main(args)
  File "src/graph2vec.py", line 126, in main
    save_embedding(args.output_path, model, graphs, args.dimensions)
  File "src/graph2vec.py", line 99, in save_embedding
    out.append([int(identifier)] + list(model.docvecs["g_"+identifier]))
  File "C:\AppData\Local\Programs\Python\Python37\lib\site-packages\gensim\models\keyedvectors.py", line 1613, in __getitem__
    raise KeyError("tag '%s' not seen in training corpus/invalid" % index)
KeyError: "tag 'g_0' not seen in training corpus/invalid"
```

Thank you

**Comment by AkshatSood** [comment]
The issue was resolved by changing the way the code split the path of the dataset. Since I was using Windows, the paths used "\" instead of "/".

**Comment by benedekrozemberczki** [comment]
I would recommend using the KarateClub library.
