### ISSUE TITLE
Error on executing graph2vec.py

### ISSUE THREAD

**Issue by efotopoulou** [benedekrozemberczki/graph2vec#43]
After installing all required packages and executing the graph2vec.py i got the following error. 
Any help is more than welcome

```
python src/graph2vec.py
Traceback (most recent call last):
  File "src/graph2vec.py", line 10, in <module>
    from joblib import Parallel, delayed
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/eleni/Documents/PythonProjects/graph2vec/venv/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```

**Comment by benedekrozemberczki** [comment]
Dear @efotopoulou,  Can you used the karateclub library on my main github page?
