### ISSUE TITLE
error with custom data

### ISSUE THREAD

**Issue by youjin-c** [benedekrozemberczki/graph2vec#6]
I've changed my data as your dataset format, and check the name of files are integer and all of them json validated but got this error. 
```
Feature extraction started.

100%|█████████████████████████████████████████████████████████████████████████████████████████| 741/741 [00:00<00:00, 819.88it/s]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "src/graph2vec.py", line 84, in feature_extractor
    graph, features, name = dataset_reader(path)
  File "src/graph2vec.py", line 67, in dataset_reader
    graph = nx.from_edgelist(data["edges"])
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/networkx/convert.py", line 390, in from_edgelist
    G.add_edges_from(edgelist)
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/networkx/classes/graph.py", line 969, in add_edges_from
    "Edge tuple %s must be a 2-tuple or 3-tuple." % (e,))
networkx.exception.NetworkXError: Edge tuple [] must be a 2-tuple or 3-tuple.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/graph2vec.py", line 131, in <module>
    main(args)
  File "src/graph2vec.py", line 115, in main
    document_collections = Parallel(n_jobs = args.workers)(delayed(feature_extractor)(g, args.wl_iterations) for g in tqdm(graphs))
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/EUGENE/anaconda3/envs/thesis/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
networkx.exception.NetworkXError: Edge tuple [] must be a 2-tuple or 3-tuple.
```
attaching one of my json files.
```
0101.json
{"edges": [[2, 3], [3, 4], [3, 5], [4, 8], [4, 10], [5, 6], [5, 16], [6, 22], [6, 114], [8, 9], [9, 17], [9, 18], [10, 20], [10, 61], [10, 21], [11, 12], [11, 13], [12, 66], [12, 78], [13, 14], [13, 15], [16, 24], [16, 25], [17, 26], [17, 28], [18, 19], [19, 29], [19, 30], [20, 93], [21, 33], [21, 35], [22, 23], [23, 36], [23, 37], [24, 38], [24, 40], [25, 43], [25, 41], [25, 44], [25, 45], [26, 27], [27, 46], [27, 47], [28, 51], [29, 52], [29, 53], [30, 54], [30, 92], [32, 58], [32, 64], [33, 34], [34, 68], [34, 79], [35, 76], [35, 80], [36, 11], [37, 11], [38, 39], [39, 82], [39, 87], [40, 115], [40, 83], [47, 48], [48, 49], [48, 50], [49, 25], [50, 81], [54, 55], [55, 94], [55, 98], [55, 107], [56, 57], [56, 60], [58, 59], [59, 62], [59, 63], [61, 104], [61, 106], [64, 65], [65, 102], [66, 70], [66, 74], [70, 71], [71, 72], [71, 103], [79, 86], [79, 88], [83, 85], [83, 84], [88, 89], [89, 90], [89, 91], [92, 56], [93, 31], [93, 32], [94, 96], [94, 100], [96, 97], [104, 105], [105, 107], [105, 109], [106, 111], [106, 113], [109, 110], [111, 112], [114, 61]], "features": {"2": "1", "3": "3", "4": "3", "5": "3", "8": "2", "10": "4", "6": "3", "16": "3", "22": "2", "114": "2", "9": "3", "17": "3", "18": "2", "20": "2", "61": "4", "21": "3", "11": "4", "12": "3", "13": "3", "66": "3", "78": "1", "14": "1", "15": "1", "24": "3", "25": "6", "26": "2", "28": "2", "19": "3", "29": "3", "30": "3", "93": "3", "33": "2", "35": "3", "23": "3", "36": "2", "37": "2", "38": "2", "40": "3", "43": "1", "41": "1", "44": "1", "45": "1", "27": "3", "46": "1", "47": "2", "51": "1", "52": "1", "53": "1", "54": "2", "92": "2", "32": "3", "58": "2", "64": "2", "34": "3", "68": "1", "79": "3", "76": "1", "80": "1", "39": "3", "82": "1", "87": "1", "115": "1", "83": "3", "48": "3", "49": "2", "50": "2", "81": "1", "55": "4", "94": "3", "98": "1", "107": "2", "56": "3", "57": "1", "60": "1", "59": "3", "62": "1", "63": "1", "104": "2", "106": "3", "65": "2", "102": "1", "70": "2", "74": "1", "71": "3", "72": "1", "103": "1", "86": "1", "88": "2", "85": "1", "84": "1", "89": "3", "90": "1", "91": "1", "31": "1", "96": "2", "100": "1", "97": "1", "105": "3", "109": "2", "111": "2", "113": "1", "110": "1", "112": "1"}}
```

**Comment by benedekrozemberczki** [comment]
Could you send the JSON which causes the failure?

**Comment by youjin-c** [comment]
they don't let me upload .json files,
here's [link](https://drive.google.com/drive/folders/1U56l1vkqayZVielmOkWdGundo0MUgKqz?usp=sharing) of google drive.

**Comment by benedekrozemberczki** [comment]
Can You remove the trailing zeros and reindex the json files from zero?

**Comment by youjin-c** [comment]
will try and report back to you soon. Thank you for fast replying.

**Comment by youjin-c** [comment]
I reindexed all json files starting from zero, got the same error.

**Comment by benedekrozemberczki** [comment]
Can you tell the index of the json which fails?

**Comment by youjin-c** [comment]
I just tested for a small batch for a test.
When I put 0-10.json it worked fine.
But when I put 11.json and 12.json together, I got the error.
when I put 11.json and 12.json separately. it was okay.

**Comment by youjin-c** [comment]
Oh I think 11.json file has some empty lists. I will fix them try again.

**Comment by youjin-c** [comment]
After erased all empty lists, everything worked fine without reindexing from zero.
Thank you!!!!

**Comment by SihamAmarouche** [comment]
@youjinChung How can I create this json file ? thanks

**Comment by benedekrozemberczki** [comment]
Hi there,

I would recommend using this:

https://github.com/benedekrozemberczki/karateclub/

**Comment by mar-alk** [comment]
Hi
I need to run graph2vec on the datasets I have but they are in gexf format 
Is there a way to convert gexf file to json files?
@youjinChung @benedekrozemberczki

**Comment by benedekrozemberczki** [comment]
Yes. You can write a Python script.
